server:
  port: 9000

logging:
  level:
    org:
      springframework:
        security: TRACE

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub

#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id:
#            client-secret:

