server:
  port: 9000

logging:
  level:
    org:
      springframework:
        security: TRACE

#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 334278454129-olum7nmv5u41b4vqn0abivab59qe4d6h.apps.googleusercontent.com
#            client-secret: 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

