logging:
  level:
    org:
      springframework:
        security: TRACE

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/authdemo
        registration:
          keycloak:
            provider: keycloak
            client-id: authdemo
            client-secret: euwl0gsME8uqfi3WdrVfalXjtpln83dc
            scope: openid, profile, email, roles

jwt:
  jwk-set-uri: http://localhost:8081/realms/authdemo/protocol/openid-connect/certs
